### ISSUE TITLE
Max CPUs

### ISSUE THREAD

**Issue by ramezrafla** [nathanschwarz/meteor-cluster#1]
Hey Nathan, great work!

This is precisely what Meteor was missing. I worked on the edge caching server (https://github.com/ramezrafla/redis-oplog) and next would have been workers to do the heavy-lifting.

A quick question, shouldn't MAX_WORKERS be equal to cpu length - 1 .. since Master is already taking a core?

**Comment by karthage-spartacus** [comment]
Hi,

`MAX_WORKERS` is a reference value to know exactly how much cpus you have, it's the default value but it's not meant to be used as default in production :
- you'll often have a reversed proxy running on your server, and depending on the traffic you'll have, you'll need to allocate cpus to it (at least one).
- if you host your database on the same server you'll need at least 1 cpu.
- if you host an external service such as redis or elastic search you'll need 1 cpu for these.

`MAX_WORKERS` enables you to know exactly how much cpus you have, and also sets a limit to how much apps should run at the same time; but it's up to you to understand your needs and calculate how much cpus you can allocate based **on your system capacities**.

That's why the value is not set to cpu.length - 1.

**Comment by ramezrafla** [comment]
Thanks Nathan,

My concern with users is that they don't read docs thoroughly and will start using the package with default values then hit problems. I am just forecasting issues before they arise :)

Thanks

**Comment by karthage-spartacus** [comment]
You're right about that, I didn't make a clear statement about it. 
I will add a clear warning both in code and documentation about the default value and how it should be calculated.

**Comment by ramezrafla** [comment]
:+1: 
Merci!
